using System;
using Orleans;

namespace Client
{
	public class MasterConfiguration
	{
        public IClusterClient orleansClient;

        // step 0
        public bool healthCheck = true;

        // step 1
        public bool ingestion = true;

        // step 2
        public bool transactionSubmission = true;

        // in future, constraint checking

        // whether should read events generated by microservices
        public bool streamEnabled = false;

        public bool cleanup = false;

    }
}

