using System;
using Client.DataGeneration;
using Client.DataGeneration.Real;
using Common.Ingestion.Config;
using Common.Scenario;
using Orleans;

namespace Client.Execution
{
	public class MasterConfiguration
	{
        public IClusterClient orleansClient;

        // step
        public bool healthCheck = true;

        // step
        public bool load = true;

        public SyntheticDataSourceConfiguration syntheticConfig = null;

        public OlistDataSourceConfiguration olistConfig = null;

        // step
        public bool ingestion = true;

        public IngestionConfiguration ingestionConfig = null;

        // step
        public bool transaction = true;

        public ScenarioConfiguration scenarioConfig;

        // in future, constraint checking

        // whether should read events generated by microservices
        public bool streamEnabled = false;

        // submit requests to clean data created as part of the transaction submission e.g., orders, payments, shipments, carts, etc
        public bool cleanup = false;

    }
}

